### ISSUE TITLE
arbitrum goerli explorer api error

### ISSUE THREAD

**Issue by nanaliulei** [OffchainLabs/blockscout#36]
*Describe your issue here.*

https://goerli-rollup-explorer.arbitrum.io/api?module=account&action=txlist return something went wrong for almost a week.

### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by Twizzle1** [comment]
Once corrected one should allow search and collection of token and or node for contribution purposes

**Comment by rachel-bousfield** [comment]
Thanks for opening this issue, though I'm afraid we don't plan on supporting blockscout's public API at this time.
We'll notify if that changes in the future
