### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by Twizzle1** [OffchainLabs/blockscout#37]
*Describe your issue here.*
I moved too fast trying to implement the token. I didn't quite follow instructions and caused my node to crash. Causing multiple others  like explained before to me while I was correcting other mistakes
### Environment

* Elixir & Erlang/OTP versions (`elixir -version`):
* Operating System:
* Blockscout Version/branch: 

### Steps to reproduce

*Tell us how to reproduce this issue.  ❤️ if you can push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected behaviour

*Tell us what should happen.*

### Actual behaviour

*Tell us what happens instead.*

**Comment by rachel-bousfield** [comment]
Closing as per #36
-  #36

**Comment by Twizzle1** [comment]
Remember code of conduct will ensure all assets to contributing guidelines bottom line. As for #36 if that is in fact the assignee direction copilot will effect. Again there are two separate contracts.

**Comment by Twizzle1** [comment]
One will branch locally and the other is left to optimize
